CMSWeb/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using CMSWeb.Models;
using System.Diagnostics;
using BUS;
using ModelProject.Models;
using CMSWeb.ViewModels.CustomerViewModel;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;
namespace CMSWeb.Controllers
{
    [Authorize(Roles = "2,5")]
    public class CustomerController : Controller
    {
        private readonly ILogger<CustomerController> _logger;
        private readonly IBusCustomer busCustomer;
        public CustomerController(ILogger<CustomerController> logger, IBusCustomer busCustomer)
        {
            _logger = logger;
            this.busCustomer = busCustomer;
        }

       
        ListModel listModel = ListModel.GetList();

        public void GetListCustomer()
        {
            listModel.customers = busCustomer.GetCustomers();

        }

        [Route("ShowCustomer")]
        public IActionResult ShowCustomer(int page = 1)
        {
            var customers = busCustomer.GetCustomers().ToPagedList(page, 10);

            return View(customers);
        }

        [HttpGet]
        [Route("FormUpdateCustomer")]
        public IActionResult FormUpdateCustomer(string CustomerPhone)
        {
            var Customer = new CustomerDetailViewModel();
            Customer.createCustomer = busCustomer.GetCustomerByphone(CustomerPhone);
            return View(Customer);
        }

        [HttpPost]
        [Route("UpdateCustomer")]
        public IActionResult UpdateCustomer(CustomerDetailViewModel Customer)
        {
            Customer.createCustomer = busCustomer.UpdateCustomer(Customer.createCustomer);
            Customer.message = true;
            return View("FormUpdateCustomer", Customer);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
            public IActionResult Error()
            {
                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }
}

CMSWeb/Controllers/PurchaseOrderController.cs
using Microsoft.AspNetCore.Mvc;
using CMSWeb.Models;
using System.Diagnostics;
using BUS.Services;
using ModelProject.Models;
using Newtonsoft.Json;
using CMSWeb.Models.ProductBrands;
using ModelProject.ViewModel;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace CMSWeb.Controllers
{


    [Authorize(Roles = "4,5")]
    
   
    public class PurchaseOrderController : Controller
    {

        private readonly ILogger<PurchaseOrderController> _logger;
        private readonly IBusPurchaseOrder iBusPurchaseOrder;

        public PurchaseOrderController(ILogger<PurchaseOrderController> logger, IBusPurchaseOrder busPurchaseOrder)
        {
            _logger = logger;
            iBusPurchaseOrder = busPurchaseOrder;

        }

        /// <summary>
        /// danh sách hóa đơn
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var viewModel = iBusPurchaseOrder.GetListPurchaseOrderViewModels();
            return View(viewModel);
        }


        /// <summary>
        /// Lấy thông tin chi tiết cho đơn hàng
        /// </summary>
        /// <param name="OrderId">mã đơn hàng</param>
        /// <returns></returns>
        [HttpPost]
        [Route("/PurchaseOrderDetail")]
        public string Details(string OrderId)
        {
            JsonSerializerOptions options = new()
            {
                ReferenceHandler = ReferenceHandler.Preserve,
                WriteIndented = true
            };
            var data = iBusPurchaseOrder.GetPurchaseOrderById(OrderId);
            string tylerJson = System.Text.Json.JsonSerializer.Serialize(data, options);
            return tylerJson;
        }

       
        [HttpGet]
        [Route("/Delivering")]
        public IActionResult UpdateStatusOrder(string OrderId, int status)
        {
            var viewModel = iBusPurchaseOrder.DeliveringUpdateStatusOrder(OrderId, status);
            return View("Index", viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CMSWeb/Controllers/TypeController.cs
using CMSWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using BUS.Services;
using Newtonsoft.Json;
using X.PagedList;
using ModelProject.ViewModel;
using Microsoft.AspNetCore.Authorization;

namespace CMSWeb.Controllers
{

    [Authorize(Roles = "1,5")]
    public class TypeController : Controller
    {
        private readonly ILogger<TypeController> _logger;

        private readonly IBusProductType Ibus_ProductType;
      
       
        public TypeController(ILogger<TypeController> logger, IBusProductType Ibus_ProductType)
        {
            _logger = logger;
            this.Ibus_ProductType = Ibus_ProductType;

        }
        //ListModel listModel = ListModel.GetList();
        ////
        
        ////load form lại thêm thông số kỹ thuật
        [HttpGet]
        [Route("FormSpecification")]
        public IActionResult FormSpecification(string TypeId)
        {
            var Specification = new CreateProductPecification();
            Specification.typeId = TypeId;
            return View("FormSpecification", Specification);
        }


        [HttpGet]
        [Route("ShowFormSpecification")]
        public IActionResult ShowFormSpecification(int idSpecification, string TypeId)
        {
            var InformationId = new CreateInformationProperty();
            InformationId.SpecificationId = idSpecification;
            InformationId.typeId = TypeId;
            return View("FormProperty", InformationId);
        }

        /// <summary>
        /// Hiện danh sách ngành hàng
        /// </summary>
        /// <returns>ShowType.cshtml</returns>
        /// <returns>Danh sách ngành hàng</returns>
        [Route("ShowType")]
        public IActionResult ShowType(int page = 1)
        {
            var viewModel = Ibus_ProductType.ReadAll().ToPagedList(page, 10);
            return View("ShowType", viewModel);
        }


        /// <summary>
        /// lấy danh sách ngành hàng
        /// </summary>
        /// <returns></returns>
        //public ListProductTypeViewModel GetListProductTypeViewModel()
        //{
        //    var listProducttype = new ListProductTypeViewModel();
        //    var  = Ibus_ProductType.ReadAll();
        //    return listProducttype;
        //}

        ////load trang thêm ngành hàng
        
        [Route("Formtype")]
        public IActionResult Formtype()
        {
            return View("Formtype", new CreateProductType());
        }




        /// <summary>
        /// xử lý thêm mới thông tin ngành hàng
        /// </summary>
        /// <param name="productType">thông tin ngành hàng</param>
        /// <returns>thêm thành công chuyển sang form thêm thông tin kỹ thuật</returns>
        /// <returns>thêm thất bại load lại trang thêm thông tin ngành hàng</returns>
        [HttpPost]
        [Route("Type/AddType")]
        public IActionResult AddType(CreateProductType productType)
        {
            if (Ibus_ProductType.BusAddType(productType) != true)
            {
                // Nếu lỗi load lại trang thêm ngành hàng
                productType.message = true;
                return View("Formtype", productType);
            }
            var Specification = new CreateProductPecification();
            Specification.typeId = productType.typeId;
            return View("FormSpecification", Specification);
        }


        /// <summary>
        /// xử lý thêm thông số kỹ thuật sản phẩm
        /// </summary>
        /// <param name="productSpecification">thông tin thông số kỹ thuật</param>
        /// <returns></returns>
        [HttpPost]
        [Route("AddSpecification")]
        public IActionResult AddSpecification(CreateProductPecification productSpecification)
        {

            var SpecificationsId = Ibus_ProductType.BusAddProductPecification(productSpecification);
            var Information = new CreateInformationProperty();
            Information.SpecificationId = SpecificationsId;
            return View("FormProperty", Information);
        }



        /// <summary>
        /// xử lý thêm thuộc tính thông số
        /// </summary>
        /// <param name="createInformationProperty">thông tin thuộc tính thông số kỹ thuật</param>
        /// <returns>FormProperty: hiện lại view form nhập thông tin thuộc tính</returns>
        /// <returns>Thông tin view model thuộc tính</returns>
        [HttpPost]
        [Route("AddProperty")]
        public IActionResult AddProperty(CreateInformationProperty createInformationProperty)
        {
            Ibus_ProductType.BusAddInformationProperties(createInformationProperty);
            createInformationProperty.typeId = Ibus_ProductType.GetTypeIdBySpecification(createInformationProperty.SpecificationId);
            return View("FormProperty", createInformationProperty);
        }



        /// <summary>
        /// Hiện chi tiết thông tin ngành hàng
        /// </summary>
        /// <param name="typeid">mã ngành hàng</param>
        /// <returns>producttypeDetail</returns>
        [HttpGet]
        [Route("ShowTypeDetail")]
        public IActionResult ShowTypeDetail(string typeid)
        {
            var itemCheck = Ibus_ProductType.BusReadType(typeid);
            if (itemCheck == null)
            {
                return ShowType();
            }
            return View("ShowTypeDetail", itemCheck);
        }


        /// <summary>
        /// cập nhật thông tin ngành hàng
        /// </summary>
        /// <param name="productTypeDetail">thông tin chi tiết của ngành hàng</param>
        /// <returns>ShowTypeDetail</returns>
        /// <returns>thông tin chi tiết ngành hàng</returns>
        [HttpPost]
        [Route("UpdataType")]
        public IActionResult UpdataType(ProductTypeDetail productTypeDetail)
        {
           var value = Ibus_ProductType.BusUpdateType(productTypeDetail);
            return View("ShowTypeDetail", value);
        }





        [HttpGet]
        [Route("DeleteProperty")]
        public IActionResult DeleteProperty(int id, string typeid)
        {
            var ProductDetail = new ProductTypeDetail();
           
            if (Ibus_ProductType.DeleteInformationProperty(id) == true){
                ProductDetail = Ibus_ProductType.BusReadType(typeid);
                ProductDetail.messageDelete = "removePropertyRemoveTrue";
            }
            else
            {
                ProductDetail = Ibus_ProductType.BusReadType(typeid);
                ModelState.AddModelError("ErrorType", "Không thê xóa thông số của ngành hàng");
            }
            return View("ShowTypeDetail", ProductDetail);
        }


        [HttpGet]
        [Route("DeleteSpecification")]
        public IActionResult DeleteSpecification(int id, string typeid)
        {
            var ProductDetail = new ProductTypeDetail();

            if (Ibus_ProductType.deleteSpecificatio(id) == true)
            {
                ProductDetail = Ibus_ProductType.BusReadType(typeid);
                ProductDetail.messageDelete = "removeSpecificationRemoveTrue";
            }
            else
            {
                ProductDetail = Ibus_ProductType.BusReadType(typeid);
                
                ModelState.AddModelError("ErrorType", "Không thê xóa thông số của ngành hàng");
            }

            return View("ShowTypeDetail", ProductDetail);
        }

       

        [HttpGet]
        [Route("DeleteType")]
        public IActionResult DeleteType(string typeid)
        {
            var ProductDetail = Ibus_ProductType.BusReadType(typeid);
            if (Ibus_ProductType.deletetype(typeid) == true) return ShowType();
            else
            {
                
                ModelState.AddModelError("ErrorType", "Không thê xóa thông số của ngành hàng");
            }
            return View("ShowTypeDetail", ProductDetail);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CMSWeb/Controllers/UserController.cs
using CMSWeb.Models;
using Microsoft.AspNetCore.Mvc;
using ModelProject.ViewModel;
using System.Diagnostics;
using BUS.Services;
using Microsoft.AspNetCore.Authorization;

namespace CMSWeb.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IBusUser iBusUser;
        private readonly ILogger<UserController> _logger;
        public UserController(ILogger<UserController> logger, IBusUser iBusUser)
        {
            _logger = logger;
            this.iBusUser = iBusUser;
       
        }

        [Authorize(Roles = "5")]
        /// <summary>
        /// load form nhap thong tin nhan vien
        /// </summary>
        /// <returns></returns>
        [Route("FormAddUser")]
        public IActionResult FormAddUser()
        {
            var viewModel = new AddUserViewModel();
            return View("FormAddUser", viewModel);
        }

        [Authorize(Roles = "5")]
        /// <summary>
        /// Thêm quản trị vien
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddUser(AddUserViewModel viewModel)
        {
            viewModel = iBusUser.UserAdd(viewModel);
            ModelState.AddModelError("UserId", viewModel.UserId.ToString());
            return View("FormAddUser", viewModel);
        }

        [Authorize(Roles = "5")]
        /// <summary>
        /// show danh sách nhân viên
        /// </summary>
        /// <returns>ShowUsers</returns>
        /// <returns>List ListUserViewModel</returns>
        public IActionResult ShowUsers()
        {
            var viewModel = iBusUser.GetUsers();
            return View("ShowUsers", viewModel);
        }


        /// <summary>
        /// form hiện thông tin chi tiết nhân viên
        /// </summary>
        /// <param name="UserId">mã nhân viên</param>
        /// <returns>Vew ShowUserDetail</returns>
        /// <returns>EditUserViewModel</returns>
        [HttpGet]
        [Route("User/ShowUserDetail")]
        public IActionResult ShowUserDetail(int UserId)
        {
            EditUserViewModel viewModel = iBusUser.GetEditUserViewModel(UserId);
            return View(viewModel);
        }
        /// <summary>
        /// cập nhật thông tin user
        /// </summary>
        /// <param name="viewModel">thông tin chuyển từ view</param>
        /// <returns></returns>
        public IActionResult UpdateUser(EditUserViewModel viewModel)
        {
            viewModel = iBusUser.UpdateUser(viewModel);
            return View("ShowUserDetail", viewModel);
        }

        
        public IActionResult UpdatePass(int Userid)
        {
            EditUserViewModel viewModel = iBusUser.UpdatePassword(Userid);
            return View("ShowUserDetail", viewModel);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CMSWeb/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using ModelProject.ViewModel;
@{
    Role role = new Role();
    var RoleUser = User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value;
    var RoleName = role.GetRoleUser(int.Parse(RoleUser));
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMSWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CMSWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <script type="text/javascript" src="~/js/Chart.min.js"></script>

    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.ico" />
</head>
<body>
    <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html"><img src="~/assets/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="@User.FindFirst(u => u.Type == ClaimTypes.CookiePath)?.Value" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">@User.FindFirst(u => u.Type == ClaimTypes.Name)?.Value</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                   
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/logout">
                        <i class="mdi mdi-logout me-2 text-primary"></i> Signout
                    </a>
                </div>
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
                <a class="nav-link">
                    <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                </a>
            </li>
     
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>
<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_sidebar.html -->
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
            <li class="nav-item nav-profile">
                <a href="#" class="nav-link">
                    <div class="nav-profile-image">
                        <img src="@User.FindFirst(u => u.Type == ClaimTypes.CookiePath)?.Value" alt="profile">
                        <span class="login-status online"></span>
                        <!--change to offline or busy as needed-->
                    </div>
                    <div class="nav-profile-text d-flex flex-column">
                        <span class="font-weight-bold mb-2">@User.FindFirst(u => u.Type == ClaimTypes.Name)?.Value</span>
                        <span class="text-secondary text-small">@RoleName</span>
                    </div>
                    <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                </a>
            </li>
                @if (User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "6" || @User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "5"){
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Statistical" asp-action="Statistical">
                            <span class="menu-title">Dashboard</span>
                            <i class="mdi mdi-home menu-icon"></i>
                        </a>
                    </li>
                }
                @if (User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "1" || @User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "5")
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="ShowBrands">
                            <span class="menu-title">Thương hiệu</span>
                            <i class="mdi mdi-format-list-bulleted menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Type" asp-action="ShowType">
                            <span class="menu-title">Ngành hàng</span>
                            <i class="mdi mdi-format-list-bulleted menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Product" asp-action="ShowProduct">
                            <span class="menu-title">Sản phẩm</span>
                            <i style="color:red;" class="mdi mdi-cellphone-link menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProductPromotion" asp-action="Index">
                            <span class="menu-title">Khuyến mãi sản phẩm</span>
                            <i style="color:red;" class="mdi mdi-cellphone-link menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProductPromotion" asp-action="PriceSale">
                            <span class="menu-title">Giảm giá sản phẩm</span>
                            <i style="color:red;" class="mdi mdi-cellphone-link menu-icon"></i>
                        </a>
                    </li>
            }

                @if (User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "2" || User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "5")
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Customer" asp-action="ShowCustomer">
                            <span class="menu-title">Khách hàng</span>
                            <i style="color:red;" class="mdi mdi-cellphone-link menu-icon"></i>
                        </a>
                    </li>
                }

                @if (User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "2" || User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "4" || User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "5")
                {
              <li class="nav-item">
                <a class="nav-link" asp-controller="PurchaseOrder" asp-action="Index">
                    <span class="menu-title">Đơn hàng</span>
                    <i style="color:red;" class="mdi mdi-cellphone-link menu-icon"></i>
                </a>
            </li>  
                }

               @if(User.FindFirst(u => u.Type == ClaimTypes.Role)?.Value == "5"){
             <li class="nav-item">
                <a class="nav-link" asp-controller="User" asp-action="ShowUsers">
                    <span class="menu-title">Nhân viên</span>
                    <i style="color:red;" class="mdi mdi-cellphone-link menu-icon"></i>
                </a>
            </li>  

                }
        </ul>
    </nav>
    <!-- partial -->
    <div class="main-panel">
       
            @RenderBody()
      </div>
          <!-- main-panel ends -->
 </div>
      <footer class="footer container">
        <div class="container-fluid d-flex justify-content-between">
          <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
          <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
        </div>
      </footer>
      <!-- page-body-wrapper ends -->
   </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>


    <script src="~/js/RegexJs.js" asp-append-version="true"></script>
    <script src="~/js/Brands.js" asp-append-version="true"></script>
    <script src="~/js/RegexColor.js" asp-append-version="true"></script>
    
    <script src="~/js/RegexProduct.js" asp-append-version="true"></script>
    <script src="~/js/RegexSpecification.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/UploadImage.js" asp-append-version="true"></script>
    <script src="~/js/PurchaseOrder.js" asp-append-version="true"></script>
    <script src="~/js/RegexUser.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)

    
    
    <!-- endinject -->
    <!-- Plugin js for this page -->
    
    <script src="~/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
  
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/assets/js/dashboard.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>